#ifndef ISENSORMEASURE_H
#define ISENSORMEASURE_H

typedef enum ISENSORMEASURE_RESULT_E
{
    ISENSORMEASURE_OK_E = 0,
    ISENSORMEASURE_NULLPTR_ERROR_E,
    ISENSORMEASURE_ERROR_E
} ISENSORMEASURE_RESULT_T;

typedef struct ISENSORMEASURE_S ISENSORMEASURE_T;
typedef struct ISENSORMEASURE_S
{
    ISENSORMEASURE_RESULT_T (*eMeasure)(ISENSORMEASURE_T *pSelf, float *pfValue, const float fOffset, uint32_t u32ms);
} ISENSORMEASURE_T;

#endif // ISENSORMEASURE_H